language: cpp

stages:
  - name: docker_build_depends
  - name: docker_build_publish
  - name: docker_deploy
  - name: build_depends
  - name: build_publish

jobs:
  include:
      - stage: docker_build_depends
        services: docker
        dist: xenial
        before_install:
          - bash build_base1804_image.sh
          - bash build_mmo-server-depends.sh
        script: bash ./docker_push_depends.sh
      - stage: docker_build_publish
        services: docker
        dist: xenial
        before_install: 
        - bash docker_pull_depends.sh
        - bash create_network.sh
        - link_codedir.sh
        script: bash build_publish_image.sh
      - stage: docker_deploy
        services: docker
        dist: xenial
        script: ./docker_push_publish.sh

      - stage: build_depends
        dist: bionic
        sudo: true
        before_install: server-depends/src/aptget_install.sh
        script: bash server-depends/src/build_all.sh
      - stage: build_publish
        dist: bionic
        sudo: true
        script: server-code/releasebuild.sh

