language: c++

jobs:
  include:
    - dist: xenial
      services: docker
      - stage: build_depends
        before_install:
          - build_base1804_image.sh
          - build_mmo-server-depends.sh
        script: ./docker_push_depends.sh
      - stage: build_publish
        before_install: 
        - docker_pull_depends.sh
        - create_network.sh
        - link_codedir.sh
        script: build_publish_image.sh
      - stage: deploy
        script: ./docker_push_publish.sh
    - dist: bionic
      - stage: build_depends
        before_install:
        - server-depends/src/aptget_install.sh
      script: server-depends/src/build_all.sh
      - stage: build_publish
        script: server-code/releasebuild.sh

