language: c++
services: 
  - docker
dist: bionic

jobs:
  include:
    - name: "ubuntu 16.04"
      stages:
      - stage: build_depends
        before_install:
          - bash build_base1804_image.sh
          - bash build_mmo-server-depends.sh
        script: bash ./docker_push_depends.sh
      - stage: build_publish
        before_install: 
        - bash docker_pull_depends.sh
        - bash create_network.sh
        - link_codedir.sh
        script: bash build_publish_image.sh
      - stage: deploy
        script: ./docker_push_publish.sh
    - name: "ubuntu 18.04"
      stages:
      - stage: build_depends
        before_install: server-depends/src/aptget_install.sh
        script: bash server-depends/src/build_all.sh
      - stage: build_publish
        script: server-code/releasebuild.sh

