language: cpp
services: 
  - docker
dist: bionic
sudo: true

compiler:
  - clang
  - gcc

stages:
  - name: docker_build_depends
    if: compiler = gcc  
  - name: docker_build_publish
    if: compiler = gcc  
  - name: docker_deploy
    if: compiler = gcc  
  - name: build_depends
    if: compiler = clang  
  - name: build_publish
    if: compiler = clang  

jobs:
  include:
      - stage: docker_build_depends
        before_install:
          - bash build_base1804_image.sh
          - bash build_mmo-server-depends.sh
        script: bash ./docker_push_depends.sh
      - stage: docker_build_publish
        before_install: 
        - bash docker_pull_depends.sh
        - bash create_network.sh
        - link_codedir.sh
        script: bash build_publish_image.sh
      - stage: docker_deploy
        script: ./docker_push_publish.sh
      - stage: build_depends
        before_install: server-depends/src/aptget_install.sh
        script: bash server-depends/src/build_all.sh
      - stage: build_publish
        script: server-code/releasebuild.sh

