language: cpp
services: 
  - docker
dist: bionic

compiler:
  - clang
  - gcc

jobs:
  include:
      - 
        if: compiler = gcc
        stage: docker_build_depends
        before_install:
          - bash build_base1804_image.sh
          - bash build_mmo-server-depends.sh
        script: bash ./docker_push_depends.sh
      - 
        if: compiler = gcc
        stage: docker_build_publish
        before_install: 
        - bash docker_pull_depends.sh
        - bash create_network.sh
        - link_codedir.sh
        script: bash build_publish_image.sh
      - 
        if: compiler = gcc
        stage: docker_deploy
        script: ./docker_push_publish.sh

      - 
        if: compiler = clang
        stage: build_depends
        before_install: server-depends/src/aptget_install.sh
        script: bash server-depends/src/build_all.sh
      - 
        if: compiler = clang
        stage: build_publish
        script: server-code/releasebuild.sh

