name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt-all
      run: sudo bash server-depends/src/aptget_install.sh

    - name: cache-depends
      id: cache-depends
      uses: actions/cache@v1
      with:
        path: server-depends
        key: server-depends-${{ hashFiles('**/src/build_all.sh') }}
        restore-keys: server-depends-${{ hashFiles('**/src/build_all.sh') }}

    - name: build depends
      if: steps.cache-depends.outputs.cache-hit != 'true'
      run: bash server-depends/src/build_all.sh

    - name: configure
      run: bash server-code/releasebuild.sh