name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt-all
      run: sudo bash server-depends/src/aptget_install.sh
    - name: install-ccache
      run: sudo bash server-code/install_ccache.sh
    - name: cache-ccache
      id: cache-ccache
      uses: actions/cache@v1
      with:
        path: ~/.ccache/
        key: cache-ccache
    - name: cache-depends
      id: cache-depends
      uses: actions/cache@v1
      with:
        path: server-depends
        key: server-depends
    - name: build depends
      if: steps.cache-depends.outputs.cache-hit != 'true'
      run: bash server-depends/src/build_all.sh
    - name: configure
      run: bash server-code/releasebuild.sh