name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt-all
      run: sudo bash server-depends/src/aptget_install.sh

    - name: cache-depends-lib
      id: cache-depends-lib
      uses: actions/cache@v1
      with:
        path: server-depends/lib
        key: server-depends_lib
        restore-keys: server-depends_lib
    - name: cache-depends-bin
      id: cache-depends-bin
      uses: actions/cache@v1
      with:
        path: server-depends/bin
        key: server-depends_bin
        restore-keys: server-depends_bin


    - name: build depends
      if: steps.cache-depends-lib.outputs.cache-hit != 'true'
      run: bash server-depends/src/build_all.sh

    - name: configure
      run: bash server-code/releasebuild.sh