name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt-all
      run: sudo bash server-depends/src/aptget_install.sh
    - name: build depends
      run: bash server-depends/src/build_all.sh
    - name: configure
      run: bash server-code/releasebuild.sh